import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ThemeProvider } from "./components/toggle";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      
      >
        <ThemeProvider> {children}</ThemeProvider>
       
      </body>
    </html>
  );
}
